# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title                    : "Ruud Kassing"
title_separator          : "-"
locale                   : "en"
description: >-
  Project and research homepage of Ruud Kassing
masthead_title: " "

# Theme
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default

# Build settings
markdown: kramdown

# Outputting
# permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Europe/Amsterdam

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - serve.bat

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Ruud Kassing"
  location : "Utrecht, Netherlands"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Control System Developer at Twinn.<br />*Passionate about optimal control solutions for digital transformation in the water sector.*"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:ruud.kassing(at)rhdhv.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ruudkassing"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ruud-kassing-096876a4/"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=en&user=uNWSw2IAAAAJ"
    - label: " ResearchGate"
      icon: "fab fa-researchgate"
      url: "https://www.researchgate.net/profile/Ruud_Kassing"
    - label: " ORCID"
      icon: "fas fa-id-badge"
      url: "https://orcid.org/0000-0003-0743-1439"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ruudkassing"

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false
